version: 1.0.0
services:
  - mysql

ssh-keys:
  aaakey:
    secure: 2acGTq8F/lBsPwOyBxzzVPc9Pgj2J4QL8Juv+tHSJGkIfRw87A8nOBoDtSioAW94j6OtbbIYT/lMKofBaQdmbhuer2KHy+BgAN6SiZxVCXRSqjpQMG+fQLbAoZL5AzlE865sY7qF1FFsw5RbGK1evqy2zjvwuhQMIbGA+FsMZuCnG6Dyz/oikzTY+KxSealiTFqn0+j95od+7anIyTYjfe68NeAFIXHZuneHBuMu1/WVbggnpCKiMKslW3B6e52eSJk8TE8l6nuwz9xkysCXZwqWWk7++IWVc9dSi3oND1fP0MWUQirfpYDWmyhkrTukhcK3HDEhyFYQTVe3B8nPVA6rZwmCnwwdx+oUFXxUNUkPTWxxVKjfq+4/lzicBYENhUjTm1v4WCJfGuXJmZ9XOPB3OPt4zXrara3l93UxNgG/SH+n+PRboxhH20yONnW0dQC7cAdzor9iafrynSYQc7MK+7bLHw5K2tB5tI0RJVCY1osNG9xhTiBLUJ1IPFnrhGHpHoJIPugLwIES4ber6A2OqGK33LQabXEhTTTxcdej5ud61zxnlvQtEVISnVx7iSkytk5V6On6HUcJiK1uUEsdzMo8KowOBckM4V2PmKWrIfCP7vhtNF7LjNE0KIA78/8IDFEAqOiUWBPhcs5GBxn6RUAQaacq009OjGCm2o6yVA=RwKVbEKEqHZpjqYSOVA20LNkn9PjffjedT77GcY/yPoF2JWyYkdBPZtBfsSckAiAzjQYwSBZTOFSk+EVmuU0PrnQItx8J9xv6+vQ2NAz73Rc2E40lH/NPVLaf1P8y6SitYzwS1sd6sbFGK1GQOOmCAZ5bFGK2LMHnRTOCuAvo/4yuDf/1ELuXCNla4U6dB7az7kvaqf5Es+EXjuoPINq8Oi1zfUDBwdsQtUF66x6EfFgQdVwlBV2P63FTtFbXkUyV/RQ4oWj8WKRztxohZczbMinYsd9fmOV8VTSmQ+YC2C4MhNTue6YOLTwmdYKXwkeqLaNW4onVY7lw8fOBPEnbl8kQQp3cA89hRy1klnq4l83NUUkEouGT4MtIZFioqBLJFk0vx4OXfGaRpww6XdTpWEtJunIr8vgqGaQKbFTqsOwnxYeW2TRIcq3MeuESMnG8yXQpN3wqQcx8foZn8CqFaYk/E387evWrrwVLYy7ilXC6g7HhjASccRdxQttiX7RtJUUwjPNKzWfNwHPlQDtoIYhZeJZ79lShfG7hNZj1vFM5ka8wKrnKahE2S5S8XXpdisTgttTqnaynp6eTDDga9COIA4foGfAyhtise3QlWsZhqZIGqxFwDv2B7YYTxmSwzapH8sFRBNOUE1+xuAODStdry35Vb4+qzLwHM4G36V3c+vUCf/HB2CPAGDxMnSQ7E8pUjeuE/TzafBDnsEgV/NuPCutU1rpw3Y+rbDWOqOCxaFll8jpC2JQWJ0h6pqt5qyv8WYCH2KeVsy4E3pt4+EDF3wqlRADr4CcYwFpF4psV6Gg4lGFzsaWsq6wyNhgeXgjgQiUhjqvQnOgwP6SBLaLZXAcrSBMkoeykYY7lBstO0XiBN/0+fLz9zGXgZgzLzWbVMWeg5D1hXDgqnuv1ytCX+gHufLxMnl8J6eEHAmvF2MaGZ5bnJ6WxWuN2t7abT8q8JAeafB6Gt+XvSBOVRPf71Hd1nBvO3TQV6JBK3XLMiLQ7u2+Zag2/k+Ey80hdQp63Ih3vH/crFAsjMK4kXqxQXm/AdVkaxYtcRA5YzBK0gxPoi1N8eFPWXznRh3cOpyFDzlWQksbJ5BvdCLlbMZBUJTr9V9GCmaDdRI7SYvygmr45JCNEqWTHoBSiZgBdwbu/MpLdxCQDA9KCSSdqqe+oF/lzM33b1I9J1Jw3t6jrCUwbbqVnUtxRLwK9FbWECQNeRA4oIzlKE6vD/491cgJEQO9Rl+WZUoZxd8ws7Yp2mfPNbQ0bkbL+mNwO8y0QB7nc7fQ6yWN/KkeJxBtI9f6FzxnzaWB3ogWkZozOcVYJknJwWD/yl1/nB43rgc5oH9LyUwFCvdfYk3BSG3SOxF3Hwn9KZHpq/4gbmt686TEBPpdjHWdQhKihAFNN5cEfjo5GsiQykCn2RDhOpRKVVL/SNwMUI+1hZyFELlNM7a/OtwM9eQsGcMC7OylQKahHSOhBcAvDu1mEG+MRRA/Y1P4C4P73MLjGIiO7GHNSB2E/cri/eejDPZ8TIusRrCoPB8IPciTNJ0LFVK/rjWU+jZJaEj0Ka27fQXg8HZDYDJ/wgw3jIJi7hkQagMY65ClPz/MKSf3Prwa6vayqMG7Po6Zi+Vt+bVVwSjyVlIlqKov/O8k4zk9SWQL6twYpTn9pav75r4cZW+Tn9ZC2tdVm6Zz/iOLV5u39Ir4Wv4zyYDcMQ2xtXv/CH17omQJlnFQTZq/KJAIXqVGNKkRG8t3Bb6WSO+PXXyBTZDwS9wjYi79GsxHZbAyAqvVd4ESr+o0jJeQ+NdVjbm1tb54jLXaxvnyHhumRzXC+UlYIAiKofXOtb+SL4oNQBZ1KkvD8C+BHpZmCyZ9yX+kEJP8+0EfWHWCZc3hVPUxP66Fle8HQG6+BX6dINHXyl8JZgzHnlnoGyskllupxCLkxu8nk0sz9ha/8rtqssycdnmpZLeE0mjBTx85+3uwF7slP2QKv/iuPmbJsiHKkI5Dy2oGCAFFLv55tn2R/riw8js9juAtL/jvI2FE/K/o3UITM4VlXSll1U8JwGD7vu2Su/ITXk2k7s4CO+OSD7SxB/bHKkYxdK6Pi+3OfEjTBCRa4YZeRvOJ85YRHq/nbOMAz8017kx9SzgFCoqpU/SOgAr5HnprBBqXLWhv7A4zhtMPFrzkmuHtMT7XktnoZyV/HJnk1teSFCmFdakuMobC6ExE+BWwI5/7aEJIRaFbaMlEsY8s3JPfS+/O/XM4m6NHzMKlwwlzjyXuhn1zqYYIgfAvf9KMyvInKonJd+EZFjbmrGEqvaED5sMrDadQmp4X/6sL4jdo8X/zd0yw0cxMriYJ2fRc+P6O+58V2q+OhYv8sX07JmBzB7OvgdlHZN0iCuP57qd7XNIlVjUmxSuOh3m9SJ6h+p0=

variables:
  global:
    COMPOSER_BIN: $BUILD_DIR/vendor/bin
    BLT_DIR: $BUILD_DIR/vendor/acquia/blt

events:
  build:
    steps:
        # Install global packages and set global configuration.
        - setup:
            type: script
            script:
              - ./tests/haas/install_arachni.sh
              - composer validate --no-check-all --ansi
              - composer install
              - source ${BLT_DIR}/scripts/pipelines/setup_environment
              - source ${BLT_DIR}/scripts/pipelines/setup_project

        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - ./tests/haas/run_arachni.sh
              - ping localhost

        # Generate artifact.
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
