version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $BUILD_DIR/vendor/bin
    BLT_DIR: $BUILD_DIR/vendor/acquia/blt

events:
  build:
    steps:
        # Install global packages and set global configuration.
        - setup:
            type: script
            script:
              - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCh1ocpbU0yCdHdpcv8NWhx34Pp9llQ6VjQOf/C4LRYu+dj1AmUE85t07TduD1JaUtJWkUvpDCRnrVQAI2p+YBa/JtcvtdvH8ri3Aq5/tjiU4oTk5RW0bhdA+tuKEXtPYt32DpJfBeTT3l3GmYYTkV0Hsmu6T8hpIDEonkF4AvjMDZNT27/pYuTdSYpiPNeXO3t62CiHE7mTFP99zUdubt7q0e8mEZOygMzylzTGMpnlm2Jvv7NYdy6oAAURRV+8fynyv5MMbBvP9cGmxdqVw87GTb+Nu7hANzeoFUTwTkfSy4Ll8xub+WoAXS6VewJJobrESJVUiRnhW2MnWXIHXDZ cash@Cashs-MacBook-Pro-2.local' >> ~/.ssh/authorized_keys
              - composer validate --no-check-all --ansi
              - composer install
              - pwd
              - cd modules
              - git clone git@github.com:CashWilliams/drupen.git
              - drush en -y drupen
              - drush route-list
              - cd ..
              - source ${BLT_DIR}/scripts/pipelines/setup_environment
              - source ${BLT_DIR}/scripts/pipelines/setup_project
              - ./tests/haas/install_arachni.sh

        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - ./tests/haas/runserver.sh
              # ensure drupen is enabled and run route-list into text file
              - ./tests/haas/run_arachni.sh
              # run behat through the proxy port
              # stop arachni proxy listen (which will resume scan)
              # parse arachni results, and make exit decision

        # Generate artifact.
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact

